# Site settings
title: Resumen de mi carrera
description: A blog about lorem ipsum dolor sit amet
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Esteban Chavarro
user_description: Estudiante de ingeniería de sistemas apasionado por la industria tecnológica y sus aplicaciones para optimizar procesos, mejorar la calidad humana y ayudar a empresas a cumplir sus objetivos.
user_title: Software Developer
email: estebanchavarro13@gmail.com
twitter_username: /
github_username: estebancsi
gplus_username:  /

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
